### ISSUE TITLE
Did you method consider the absorption boundaries?

### ISSUE THREAD

**Issue by zhaoguangyuan123** [JuliaWaveScattering/MultipleScattering.jl#34]
Hi,

Nice work!

Curious that if your method has considered the absorption boundaries, such as the "perfect matched layer".

For my application, I would be more interested in the ones with open boundaries. 

Would like to hear your kind reply!

Thanks 
Guangyuan

**Comment by jondea** [comment]
Hi Guangyuan, thank you for your question and interest! The method used in this package naturally produces outgoing solutions without boundaries. This is because the scattered field is built from a basis of outgoing solutions of the relevant equation. For example, in the case of 2D acoustics, the basis functions around each particle are Hankel functions of the first kind in the radial direction and Fourier modes in the polar direction. Because of this, the method doesn't require perfectly matched layers.

**Comment by zhaoguangyuan123** [comment]
Got it. I will read your document more and try to understand it more. 

Thank you Jonathan
